/*
 * Customer Phone List
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: john.isailofski@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.isailofski.phonelist.model;

import com.isailofski.phonelist.springbootclient.model.CustomerDetailsDto;
import com.isailofski.phonelist.springbootclient.model.PhoneNumberDetailsDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CustomersNumberDto
 */
public class CustomersNumberDtoTest {
    private final CustomersNumberDto model = new CustomersNumberDto();

    /**
     * Model tests for CustomersNumberDto
     */
    @Test
    public void testCustomersNumberDto() {
        // TODO: test CustomersNumberDto
    }

    /**
     * Test the property 'customer'
     */
    @Test
    public void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'phones'
     */
    @Test
    public void phonesTest() {
        // TODO: test phones
    }

}
