/*
 * Customer Phone List
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: john.isailofski@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.isailofski.phonelist.model;

import com.isailofski.phonelist.springbootclient.model.StatusDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PhoneNumberDetailsDto
 */
public class PhoneNumberDetailsDtoTest {
    private final PhoneNumberDetailsDto model = new PhoneNumberDetailsDto();

    /**
     * Model tests for PhoneNumberDetailsDto
     */
    @Test
    public void testPhoneNumberDetailsDto() {
        // TODO: test PhoneNumberDetailsDto
    }

    /**
     * Test the property 'phoneId'
     */
    @Test
    public void phoneIdTest() {
        // TODO: test phoneId
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'phoneType'
     */
    @Test
    public void phoneTypeTest() {
        // TODO: test phoneType
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'areaCode'
     */
    @Test
    public void areaCodeTest() {
        // TODO: test areaCode
    }

    /**
     * Test the property 'phoneNum'
     */
    @Test
    public void phoneNumTest() {
        // TODO: test phoneNum
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
