/*
 * Customer Phone List
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: john.isailofski@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.isailofski.phonelist.model;

import com.isailofski.phonelist.springbootclient.model.CustomerDetailsDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PostCustomerListRequestDto
 */
public class PostCustomerListRequestDtoTest {
    private final PostCustomerListRequestDto model = new PostCustomerListRequestDto();

    /**
     * Model tests for PostCustomerListRequestDto
     */
    @Test
    public void testPostCustomerListRequestDto() {
        // TODO: test PostCustomerListRequestDto
    }

    /**
     * Test the property 'phoneDetails'
     */
    @Test
    public void phoneDetailsTest() {
        // TODO: test phoneDetails
    }

}
