/*
 * Customer Phone List
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: john.isailofski@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.isailofski.phonelist.model;

import io.swagger.annotations.ApiModel;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for StatusDto
 */
public class StatusDtoTest {
    /**
     * Model tests for StatusDto
     */
    @Test
    public void testStatusDto() {
        // TODO: test StatusDto
    }

}
