/*
 * Customer Phone List
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: john.isailofski@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.isailofski.phonelist.springbootclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.isailofski.phonelist.springbootclient.model.CustomerDetailsDto;
import com.isailofski.phonelist.springbootclient.model.PhoneNumberDetailsDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * phone number(s) for a customer
 */
@ApiModel(description = "phone number(s) for a customer")
@JsonPropertyOrder({
    CustomersNumberDto.JSON_PROPERTY_CUSTOMER,
    CustomersNumberDto.JSON_PROPERTY_PHONES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-08T13:43:47.164719+11:00[Australia/Melbourne]")
public class CustomersNumberDto {
  public static final String JSON_PROPERTY_CUSTOMER = "customer";
  private CustomerDetailsDto customer;

  public static final String JSON_PROPERTY_PHONES = "phones";
  private List<PhoneNumberDetailsDto> phones = null;

  public CustomersNumberDto customer(CustomerDetailsDto customer) {

    this.customer = customer;
    return this;
  }

  /**
   * Get customer
   * 
   * @return customer
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTOMER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerDetailsDto getCustomer() {
    return customer;
  }

  public void setCustomer(CustomerDetailsDto customer) {
    this.customer = customer;
  }

  public CustomersNumberDto phones(List<PhoneNumberDetailsDto> phones) {

    this.phones = phones;
    return this;
  }

  public CustomersNumberDto addPhonesItem(PhoneNumberDetailsDto phonesItem) {
    if (this.phones == null) {
      this.phones = new ArrayList<PhoneNumberDetailsDto>();
    }
    this.phones.add(phonesItem);
    return this;
  }

  /**
   * Get phones
   * 
   * @return phones
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PHONES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PhoneNumberDetailsDto> getPhones() {
    return phones;
  }

  public void setPhones(List<PhoneNumberDetailsDto> phones) {
    this.phones = phones;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomersNumberDto customersNumber = (CustomersNumberDto) o;
    return Objects.equals(this.customer, customersNumber.customer) &&
        Objects.equals(this.phones, customersNumber.phones);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customer, phones);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomersNumberDto {\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    phones: ").append(toIndentedString(phones)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
