/*
 * Customer Phone List
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: john.isailofski@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.isailofski.phonelist.springbootclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.isailofski.phonelist.springbootclient.model.StatusDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * the customer&#39;s details
 */
@ApiModel(description = "the customer's details")
@JsonPropertyOrder({
    CustomerDetailsDto.JSON_PROPERTY_CUSTOMER_ID,
    CustomerDetailsDto.JSON_PROPERTY_FIRST_NAME,
    CustomerDetailsDto.JSON_PROPERTY_MIDDLE_NAME,
    CustomerDetailsDto.JSON_PROPERTY_LAST_NAME,
    CustomerDetailsDto.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-08T13:43:47.164719+11:00[Australia/Melbourne]")
public class CustomerDetailsDto {
  public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
  private Integer customerId;

  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  private String firstName;

  public static final String JSON_PROPERTY_MIDDLE_NAME = "middleName";
  private String middleName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  private String lastName;

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusDto status;

  public CustomerDetailsDto customerId(Integer customerId) {

    this.customerId = customerId;
    return this;
  }

  /**
   * The ID number of the customer
   * minimum: 0
   * 
   * @return customerId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "The ID number of the customer")
  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCustomerId() {
    return customerId;
  }

  public void setCustomerId(Integer customerId) {
    this.customerId = customerId;
  }

  public CustomerDetailsDto firstName(String firstName) {

    this.firstName = firstName;
    return this;
  }

  /**
   * The first-name of the customer
   * 
   * @return firstName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Frederick", value = "The first-name of the customer")
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public CustomerDetailsDto middleName(String middleName) {

    this.middleName = middleName;
    return this;
  }

  /**
   * The middle-name of the customer (if any)
   * 
   * @return middleName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Frederick", value = "The middle-name of the customer (if any)")
  @JsonProperty(JSON_PROPERTY_MIDDLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public CustomerDetailsDto lastName(String lastName) {

    this.lastName = lastName;
    return this;
  }

  /**
   * The last-name of the customer
   * 
   * @return lastName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Frederick", value = "The last-name of the customer")
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public CustomerDetailsDto status(StatusDto status) {

    this.status = status;
    return this;
  }

  /**
   * Get status
   * 
   * @return status
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusDto getStatus() {
    return status;
  }

  public void setStatus(StatusDto status) {
    this.status = status;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerDetailsDto customerDetails = (CustomerDetailsDto) o;
    return Objects.equals(this.customerId, customerDetails.customerId) &&
        Objects.equals(this.firstName, customerDetails.firstName) &&
        Objects.equals(this.middleName, customerDetails.middleName) &&
        Objects.equals(this.lastName, customerDetails.lastName) &&
        Objects.equals(this.status, customerDetails.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, firstName, middleName, lastName, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerDetailsDto {\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
