/*
 * Customer Phone List
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: john.isailofski@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.isailofski.phonelist.springbootclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.isailofski.phonelist.springbootclient.model.StatusDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * telephone number details
 */
@ApiModel(description = "telephone number details")
@JsonPropertyOrder({
    PhoneNumberDetailsDto.JSON_PROPERTY_PHONE_ID,
    PhoneNumberDetailsDto.JSON_PROPERTY_CUSTOMER_ID,
    PhoneNumberDetailsDto.JSON_PROPERTY_PHONE_TYPE,
    PhoneNumberDetailsDto.JSON_PROPERTY_COUNTRY_CODE,
    PhoneNumberDetailsDto.JSON_PROPERTY_AREA_CODE,
    PhoneNumberDetailsDto.JSON_PROPERTY_PHONE_NUM,
    PhoneNumberDetailsDto.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-08T13:43:47.164719+11:00[Australia/Melbourne]")
public class PhoneNumberDetailsDto {
  public static final String JSON_PROPERTY_PHONE_ID = "phone_id";
  private Integer phoneId;

  public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
  private Integer customerId;

  /**
   * type of phone system in use by the number
   */
  public enum PhoneTypeEnum {
    MOBILE("mobile"),

    IP("ip"),

    LANDLINE("landline");

    private String value;

    PhoneTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PhoneTypeEnum fromValue(String value) {
      for (PhoneTypeEnum b : PhoneTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PHONE_TYPE = "phone_type";
  private PhoneTypeEnum phoneType;

  public static final String JSON_PROPERTY_COUNTRY_CODE = "country_code";
  private String countryCode;

  public static final String JSON_PROPERTY_AREA_CODE = "area_code";
  private String areaCode;

  public static final String JSON_PROPERTY_PHONE_NUM = "phone_num";
  private String phoneNum;

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusDto status;

  public PhoneNumberDetailsDto phoneId(Integer phoneId) {

    this.phoneId = phoneId;
    return this;
  }

  /**
   * The phone number reference ID
   * minimum: 0
   * 
   * @return phoneId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "The phone number reference ID")
  @JsonProperty(JSON_PROPERTY_PHONE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPhoneId() {
    return phoneId;
  }

  public void setPhoneId(Integer phoneId) {
    this.phoneId = phoneId;
  }

  public PhoneNumberDetailsDto customerId(Integer customerId) {

    this.customerId = customerId;
    return this;
  }

  /**
   * The ID number of the customer
   * minimum: 0
   * 
   * @return customerId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "The ID number of the customer")
  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCustomerId() {
    return customerId;
  }

  public void setCustomerId(Integer customerId) {
    this.customerId = customerId;
  }

  public PhoneNumberDetailsDto phoneType(PhoneTypeEnum phoneType) {

    this.phoneType = phoneType;
    return this;
  }

  /**
   * type of phone system in use by the number
   * 
   * @return phoneType
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "mobile", value = "type of phone system in use by the number")
  @JsonProperty(JSON_PROPERTY_PHONE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PhoneTypeEnum getPhoneType() {
    return phoneType;
  }

  public void setPhoneType(PhoneTypeEnum phoneType) {
    this.phoneType = phoneType;
  }

  public PhoneNumberDetailsDto countryCode(String countryCode) {

    this.countryCode = countryCode;
    return this;
  }

  /**
   * code for each country
   * 
   * @return countryCode
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "061", value = "code for each country")
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public PhoneNumberDetailsDto areaCode(String areaCode) {

    this.areaCode = areaCode;
    return this;
  }

  /**
   * code to define an std area
   * 
   * @return areaCode
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "03", value = "code to define an std area")
  @JsonProperty(JSON_PROPERTY_AREA_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAreaCode() {
    return areaCode;
  }

  public void setAreaCode(String areaCode) {
    this.areaCode = areaCode;
  }

  public PhoneNumberDetailsDto phoneNum(String phoneNum) {

    this.phoneNum = phoneNum;
    return this;
  }

  /**
   * the phone number
   * 
   * @return phoneNum
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1111222333", value = "the phone number")
  @JsonProperty(JSON_PROPERTY_PHONE_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhoneNum() {
    return phoneNum;
  }

  public void setPhoneNum(String phoneNum) {
    this.phoneNum = phoneNum;
  }

  public PhoneNumberDetailsDto status(StatusDto status) {

    this.status = status;
    return this;
  }

  /**
   * Get status
   * 
   * @return status
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusDto getStatus() {
    return status;
  }

  public void setStatus(StatusDto status) {
    this.status = status;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneNumberDetailsDto phoneNumberDetails = (PhoneNumberDetailsDto) o;
    return Objects.equals(this.phoneId, phoneNumberDetails.phoneId) &&
        Objects.equals(this.customerId, phoneNumberDetails.customerId) &&
        Objects.equals(this.phoneType, phoneNumberDetails.phoneType) &&
        Objects.equals(this.countryCode, phoneNumberDetails.countryCode) &&
        Objects.equals(this.areaCode, phoneNumberDetails.areaCode) &&
        Objects.equals(this.phoneNum, phoneNumberDetails.phoneNum) &&
        Objects.equals(this.status, phoneNumberDetails.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phoneId, customerId, phoneType, countryCode, areaCode, phoneNum, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneNumberDetailsDto {\n");
    sb.append("    phoneId: ").append(toIndentedString(phoneId)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    phoneType: ").append(toIndentedString(phoneType)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    areaCode: ").append(toIndentedString(areaCode)).append("\n");
    sb.append("    phoneNum: ").append(toIndentedString(phoneNum)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
