/*
 * Customer Phone List
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: john.isailofski@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.isailofski.phonelist.springbootclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.isailofski.phonelist.springbootclient.model.CustomerDetailsDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Activate a list of one or more phone numbers and attach them to a customer
 */
@ApiModel(description = "Activate a list of one or more phone numbers and attach them to a customer")
@JsonPropertyOrder({
    PutCustomerDetailsRequestDto.JSON_PROPERTY_CUSTOMER_DETAILS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-08T13:43:47.164719+11:00[Australia/Melbourne]")
public class PutCustomerDetailsRequestDto {
  public static final String JSON_PROPERTY_CUSTOMER_DETAILS = "customerDetails";
  private List<CustomerDetailsDto> customerDetails = null;

  public PutCustomerDetailsRequestDto customerDetails(List<CustomerDetailsDto> customerDetails) {

    this.customerDetails = customerDetails;
    return this;
  }

  public PutCustomerDetailsRequestDto addCustomerDetailsItem(CustomerDetailsDto customerDetailsItem) {
    if (this.customerDetails == null) {
      this.customerDetails = new ArrayList<CustomerDetailsDto>();
    }
    this.customerDetails.add(customerDetailsItem);
    return this;
  }

  /**
   * list of customers
   * 
   * @return customerDetails
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "list of customers")
  @JsonProperty(JSON_PROPERTY_CUSTOMER_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CustomerDetailsDto> getCustomerDetails() {
    return customerDetails;
  }

  public void setCustomerDetails(List<CustomerDetailsDto> customerDetails) {
    this.customerDetails = customerDetails;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutCustomerDetailsRequestDto putCustomerDetailsRequest = (PutCustomerDetailsRequestDto) o;
    return Objects.equals(this.customerDetails, putCustomerDetailsRequest.customerDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutCustomerDetailsRequestDto {\n");
    sb.append("    customerDetails: ").append(toIndentedString(customerDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
